"""add job scraper tables

Revision ID: 09d928c79fdf
Revises: 5e2d779a62bb
Create Date: 2026-07-21 16:50:09.165879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '09d928c79fdf'
down_revision: Union[str, None] = '5e2d779a62bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_source',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('rate_limit_per_min', sa.Integer(), nullable=True),
    sa.Column('auth_config', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_source_name'), 'job_source', ['name'], unique=True)
    op.create_table('job',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_source_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('location_raw', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('remote_type', sa.Enum('fully_remote', 'hybrid', 'onsite', 'unknown', name='remotetype'), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('apply_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['job_source_id'], ['job_source.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_source_id', 'external_id', name='uq_job_source_external_id')
    )
    op.create_index(op.f('ix_job_external_id'), 'job', ['external_id'], unique=False)
    op.create_index(op.f('ix_job_job_source_id'), 'job', ['job_source_id'], unique=False)
    op.create_table('scrape_run',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_source_id', sa.Uuid(), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'running', 'success', 'failed', name='scrapestatus'), nullable=False),
    sa.Column('jobs_found_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_source_id'], ['job_source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scrape_run_job_source_id'), 'scrape_run', ['job_source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scrape_run_job_source_id'), table_name='scrape_run')
    op.drop_table('scrape_run')
    op.drop_index(op.f('ix_job_job_source_id'), table_name='job')
    op.drop_index(op.f('ix_job_external_id'), table_name='job')
    op.drop_table('job')
    op.drop_index(op.f('ix_job_source_name'), table_name='job_source')
    op.drop_table('job_source')
    # ### end Alembic commands ###
