"""add application table

Revision ID: 32a427339816
Revises: 945239346dd7
Create Date: 2026-07-21 17:07:28.907115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '32a427339816'
down_revision: Union[str, None] = '945239346dd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('applied', 'screening', 'interview', 'offer', 'rejected', name='applicationstatus'), nullable=False),
    sa.Column('status_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_client_id'), 'application', ['client_id'], unique=False)
    op.create_index(op.f('ix_application_job_id'), 'application', ['job_id'], unique=False)
    op.create_index(op.f('ix_application_profile_id'), 'application', ['profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_profile_id'), table_name='application')
    op.drop_index(op.f('ix_application_job_id'), table_name='application')
    op.drop_index(op.f('ix_application_client_id'), table_name='application')
    op.drop_table('application')
    # ### end Alembic commands ###
