"""create core models

Revision ID: 5e2d779a62bb
Revises: 
Create Date: 2026-07-21 16:41:50.293951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5e2d779a62bb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_developer',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('bd', 'admin', name='bdrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_developer_email'), 'business_developer', ['email'], unique=True)
    op.create_table('client',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('bd_id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('current_city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('current_state', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('current_country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('active', 'paused', 'placed', 'churned', name='clientstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bd_id'], ['business_developer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_bd_id'), 'client', ['bd_id'], unique=False)
    op.create_table('target_role',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('seniority', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('must_have_keywords', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_target_role_client_id'), 'target_role', ['client_id'], unique=False)
    op.create_table('profile',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('target_role_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.Enum('resume', 'linkedin', name='profiletype'), nullable=False),
    sa.Column('variant_label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('raw_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('structured_data', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['target_role_id'], ['target_role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_client_id'), 'profile', ['client_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profile_client_id'), table_name='profile')
    op.drop_table('profile')
    op.drop_index(op.f('ix_target_role_client_id'), table_name='target_role')
    op.drop_table('target_role')
    op.drop_index(op.f('ix_client_bd_id'), table_name='client')
    op.drop_table('client')
    op.drop_index(op.f('ix_business_developer_email'), table_name='business_developer')
    op.drop_table('business_developer')
    # ### end Alembic commands ###
