"""add job match run table

Revision ID: 6cf51ae64b6d
Revises: fd87f51ba958
Create Date: 2026-07-22 06:50:41.153089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6cf51ae64b6d'
down_revision: Union[str, None] = 'fd87f51ba958'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# The `analysisstatus` enum type already exists in Postgres (created by an earlier
# migration for comparison_run/keyword_analysis/location_analysis) — create_type=False
# tells Alembic to reuse it instead of trying (and failing) to CREATE TYPE again.
_analysis_status_enum = postgresql.ENUM(
    "pending", "running", "complete", "failed", name="analysisstatus", create_type=False
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_match_run',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('candidate_job_ids', sa.JSON(), nullable=True),
    sa.Column('status', _analysis_status_enum, nullable=False),
    sa.Column('result_detail', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_match_run_client_id'), 'job_match_run', ['client_id'], unique=False)
    op.create_index(op.f('ix_job_match_run_profile_id'), 'job_match_run', ['profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_match_run_profile_id'), table_name='job_match_run')
    op.drop_index(op.f('ix_job_match_run_client_id'), table_name='job_match_run')
    op.drop_table('job_match_run')
    # ### end Alembic commands ###
