"""make comparison_run client_id nullable

Revision ID: 8e3e6fb18ec7
Revises: 49ba099da294
Create Date: 2026-07-21 23:05:48.376946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8e3e6fb18ec7'
down_revision: Union[str, None] = '49ba099da294'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comparison_run', 'client_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comparison_run', 'client_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
