"""add ai analysis tables

Revision ID: 945239346dd7
Revises: a70df6ac8a1a
Create Date: 2026-07-21 16:58:09.457346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '945239346dd7'
down_revision: Union[str, None] = 'a70df6ac8a1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_run',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('related_entity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('related_entity_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_run_agent_type'), 'agent_run', ['agent_type'], unique=False)
    op.create_table('location_analysis',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('target_role_id', sa.Uuid(), nullable=True),
    sa.Column('location_penalty_score', sa.Integer(), nullable=False),
    sa.Column('recommendation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['target_role_id'], ['target_role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_analysis_client_id'), 'location_analysis', ['client_id'], unique=False)
    op.create_table('comparison_run',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('target_role_id', sa.Uuid(), nullable=True),
    sa.Column('profile_ids', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'running', 'complete', 'failed', name='analysisstatus'), nullable=False),
    sa.Column('result_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('result_detail', sa.JSON(), nullable=True),
    sa.Column('winner_profile_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['target_role_id'], ['target_role.id'], ),
    sa.ForeignKeyConstraint(['winner_profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comparison_run_client_id'), 'comparison_run', ['client_id'], unique=False)
    op.create_table('keyword_analysis',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('target_role_id', sa.Uuid(), nullable=True),
    sa.Column('extracted_keywords', sa.JSON(), nullable=True),
    sa.Column('missing_keywords', sa.JSON(), nullable=True),
    sa.Column('ats_score', sa.Integer(), nullable=False),
    sa.Column('recruiter_attention_score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.ForeignKeyConstraint(['target_role_id'], ['target_role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keyword_analysis_profile_id'), 'keyword_analysis', ['profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_keyword_analysis_profile_id'), table_name='keyword_analysis')
    op.drop_table('keyword_analysis')
    op.drop_index(op.f('ix_comparison_run_client_id'), table_name='comparison_run')
    op.drop_table('comparison_run')
    op.drop_index(op.f('ix_location_analysis_client_id'), table_name='location_analysis')
    op.drop_table('location_analysis')
    op.drop_index(op.f('ix_agent_run_agent_type'), table_name='agent_run')
    op.drop_table('agent_run')
    # ### end Alembic commands ###
