"""add job is_used flag

Revision ID: fd87f51ba958
Revises: 8e3e6fb18ec7
Create Date: 2026-07-22 06:13:16.736626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fd87f51ba958'
down_revision: Union[str, None] = '8e3e6fb18ec7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('is_used', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'is_used')
    # ### end Alembic commands ###
